version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  app:
    build:
      context: .
    image: agentsi2a
    ports:
      - "8080:8080"
    depends_on:
      - mongo
